In [2]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np


# def kmeans_display(X, label, n_cluster):
#     plot_color = ["b^", "go", "rs"]

#     print(">> Clusters : ")
#     Xi = []
#     for i in range(0, n_cluster):
#         Xi.append(X[label == i, :])
#         print(Xi[i])
#         plt.plot(Xi[i][:, 0], Xi[i][:, 1], plot_color[i], markersize=4, alpha=.8)

#     plt.axis('equal')
#     plt.show()


n_cluster = 3
X = np.array([[1.5, 6],
              [3, 4.5],
              [2.25, 6],
              [6, 1.5],
              [7.5, 3],
              [6, 7.5],
              [4.5, 9],
              [4.5, 6]])

kmeans = KMeans(n_clusters=n_cluster, random_state=0).fit(X)
print('Các center tìm được:')
print(kmeans.cluster_centers_)

pred_label = kmeans.predict(X)
# kmeans_display(X, pred_label, n_cluster)

print("Kết quả phân nhóm : ")
for i in range(0, n_cluster):
    print("Nhóm",i+1)
    print(X[pred_label == i, :])

Các center tìm được:
[[6.75 2.25]
 [5.   7.5 ]
 [2.25 5.5 ]]
Kết quả phân nhóm : 
Nhóm 1
[[6.  1.5]
 [7.5 3. ]]
Nhóm 2
[[6.  7.5]
 [4.5 9. ]
 [4.5 6. ]]
Nhóm 3
[[1.5  6.  ]
 [3.   4.5 ]
 [2.25 6.  ]]
